[package]
name = "rostorrent"
version = "0.1.0"
authors = ["Muhammad Bhatti <mdrbhatti@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.8"
log4rs = "0.11.0"